"""Application use cases and deterministic orchestration contracts."""

from personal_shopping_agent.application.collection import (
    CandidateDiscovery,
    NoCandidatesDiscoveredError,
    ProductDetailCollector,
    SearchDetailCollectionResult,
    SearchDetailCollectionService,
    SearchDetailUnitOfWork,
    SearchDetailUnitOfWorkFactory,
)
from personal_shopping_agent.application.conversion import (
    ConvertedDetailBatch,
    DetailConversionError,
    DetailObservationConverter,
    NoDetailObservationsError,
    evidence_source_for_store,
)
from personal_shopping_agent.application.cross_check import (
    EvidenceCheck,
    EvidenceCheckStatus,
    EvidenceCrossCheckBatch,
    EvidenceCrossCheckResult,
    EvidenceCrossCheckService,
    EvidenceCrossCheckUnitOfWork,
    EvidenceCrossCheckUnitOfWorkFactory,
    NoProductsForEvidenceCheckError,
    OfficialEvidenceIdentityMismatchError,
    OfficialEvidenceProvider,
    OfficialProductObservation,
    OfficialSpecificationObservation,
    ProductEvidenceChecker,
)
from personal_shopping_agent.application.details import (
    PlatformDetailAdapter,
    PlatformDetailParseError,
    PlatformProductDetail,
    PlatformSpecificationObservation,
    PlatformVariantOption,
    ProductDetailService,
)
from personal_shopping_agent.application.discovery import (
    CandidateDiscoveryService,
    CollectedPage,
    PageCollector,
    PlatformAccessRestrictedError,
    PlatformCandidate,
    PlatformSearchAdapter,
    PlatformSearchResult,
)
from personal_shopping_agent.application.ingestion import (
    OfferIngestionResult,
    OfferIngestionService,
    OfferIngestionUnitOfWork,
    OfferIngestionUnitOfWorkFactory,
)
from personal_shopping_agent.application.observations import (
    DetailObservation,
    PlatformObservationKind,
    PlatformObservationService,
    PlatformObservationStore,
    SearchObservation,
)
from personal_shopping_agent.application.service import (
    ShoppingWorkflowService,
    next_workflow_state,
)
from personal_shopping_agent.application.workflow import (
    InvalidWorkflowTransitionError,
    ShoppingWorkflow,
    WorkflowEvent,
    WorkflowSnapshot,
    WorkflowState,
    WorkflowStateMachine,
)

__all__ = [
    "CandidateDiscovery",
    "CandidateDiscoveryService",
    "CollectedPage",
    "ConvertedDetailBatch",
    "DetailConversionError",
    "DetailObservation",
    "DetailObservationConverter",
    "EvidenceCheck",
    "EvidenceCheckStatus",
    "EvidenceCrossCheckBatch",
    "EvidenceCrossCheckResult",
    "EvidenceCrossCheckService",
    "EvidenceCrossCheckUnitOfWork",
    "EvidenceCrossCheckUnitOfWorkFactory",
    "InvalidWorkflowTransitionError",
    "NoCandidatesDiscoveredError",
    "NoDetailObservationsError",
    "NoProductsForEvidenceCheckError",
    "OfferIngestionResult",
    "OfferIngestionService",
    "OfferIngestionUnitOfWork",
    "OfferIngestionUnitOfWorkFactory",
    "OfficialEvidenceIdentityMismatchError",
    "OfficialEvidenceProvider",
    "OfficialProductObservation",
    "OfficialSpecificationObservation",
    "PageCollector",
    "PlatformAccessRestrictedError",
    "PlatformCandidate",
    "PlatformDetailAdapter",
    "PlatformDetailParseError",
    "PlatformObservationKind",
    "PlatformObservationService",
    "PlatformObservationStore",
    "PlatformProductDetail",
    "PlatformSearchAdapter",
    "PlatformSearchResult",
    "PlatformSpecificationObservation",
    "PlatformVariantOption",
    "ProductDetailCollector",
    "ProductDetailService",
    "ProductEvidenceChecker",
    "SearchDetailCollectionResult",
    "SearchDetailCollectionService",
    "SearchDetailUnitOfWork",
    "SearchDetailUnitOfWorkFactory",
    "SearchObservation",
    "ShoppingWorkflow",
    "ShoppingWorkflowService",
    "WorkflowEvent",
    "WorkflowSnapshot",
    "WorkflowState",
    "WorkflowStateMachine",
    "evidence_source_for_store",
    "next_workflow_state",
]
