"""Layer 3 - present candidate products for purchase.

Deterministic scoring, evidence confidence, ranking, reports, report access, and the optional
explanation port. Model providers and HTML rendering live in the ``llm`` and ``rendering``
adapter subpackages and are intentionally not re-exported here.
"""

from personal_shopping_agent.presentation.confidence import (
    CandidateEvidenceConfidence,
    CriterionEvidenceAssessment,
    EvidenceConfidenceEvaluator,
    EvidenceScopeMismatchError,
    InvalidEvidenceTimelineError,
)
from personal_shopping_agent.presentation.decision import (
    CandidateScoringFoundation,
    CandidateScoringFoundationBuilder,
    CriterionEvaluation,
    CriterionEvaluationStatus,
    CriterionEvaluator,
    OfferCostAssessment,
    OfferCostEstimator,
)
from personal_shopping_agent.presentation.explanation import (
    CandidateExplanation,
    ExplanationFact,
    ExplanationFallbackReason,
    ExplanationStatement,
    ExplanationStatus,
    InvalidExplanationOutputError,
    MarkdownShoppingReportExplanationRenderer,
    RenderedShoppingReportPresentation,
    ReportExplanationProvider,
    ReportExplanationProviderError,
    ReportExplanationRequest,
    ReportExplanationRequestBuilder,
    ShoppingReportExplanation,
    ShoppingReportExplanationResult,
    ShoppingReportExplanationService,
    ShoppingReportPresentationService,
    validate_explanation_scope,
)
from personal_shopping_agent.presentation.ranking import (
    BudgetStatus,
    CandidateDecisionInput,
    CandidateRankingBatch,
    CandidateRankingEngine,
    CandidateScore,
    CandidateScoringResult,
    CandidateScoringService,
    CandidateScoringUnitOfWork,
    CandidateScoringUnitOfWorkFactory,
    DuplicateCandidateError,
    NoCandidatesForScoringError,
)
from personal_shopping_agent.presentation.report_access import (
    ShoppingReportAccessService,
    ShoppingReportNotFoundError,
    ShoppingReportReader,
    StoredShoppingReportIntegrityError,
)
from personal_shopping_agent.presentation.reporting import (
    MarkdownShoppingReportRenderer,
    NoCandidateScoresForReportError,
    RenderedShoppingReport,
    ReportCandidate,
    ReportFormat,
    ReportInputMismatchError,
    ShoppingDecisionReport,
    ShoppingReportBuilder,
    ShoppingReportRenderer,
    ShoppingReportResult,
    ShoppingReportService,
    ShoppingReportUnitOfWork,
    ShoppingReportUnitOfWorkFactory,
)

__all__ = [
    "BudgetStatus",
    "CandidateDecisionInput",
    "CandidateEvidenceConfidence",
    "CandidateExplanation",
    "CandidateRankingBatch",
    "CandidateRankingEngine",
    "CandidateScore",
    "CandidateScoringFoundation",
    "CandidateScoringFoundationBuilder",
    "CandidateScoringResult",
    "CandidateScoringService",
    "CandidateScoringUnitOfWork",
    "CandidateScoringUnitOfWorkFactory",
    "CriterionEvaluation",
    "CriterionEvaluationStatus",
    "CriterionEvaluator",
    "CriterionEvidenceAssessment",
    "DuplicateCandidateError",
    "EvidenceConfidenceEvaluator",
    "EvidenceScopeMismatchError",
    "ExplanationFact",
    "ExplanationFallbackReason",
    "ExplanationStatement",
    "ExplanationStatus",
    "InvalidEvidenceTimelineError",
    "InvalidExplanationOutputError",
    "MarkdownShoppingReportExplanationRenderer",
    "MarkdownShoppingReportRenderer",
    "NoCandidateScoresForReportError",
    "NoCandidatesForScoringError",
    "OfferCostAssessment",
    "OfferCostEstimator",
    "RenderedShoppingReport",
    "RenderedShoppingReportPresentation",
    "ReportCandidate",
    "ReportExplanationProvider",
    "ReportExplanationProviderError",
    "ReportExplanationRequest",
    "ReportExplanationRequestBuilder",
    "ReportFormat",
    "ReportInputMismatchError",
    "ShoppingDecisionReport",
    "ShoppingReportAccessService",
    "ShoppingReportBuilder",
    "ShoppingReportExplanation",
    "ShoppingReportExplanationResult",
    "ShoppingReportExplanationService",
    "ShoppingReportNotFoundError",
    "ShoppingReportPresentationService",
    "ShoppingReportReader",
    "ShoppingReportRenderer",
    "ShoppingReportResult",
    "ShoppingReportService",
    "ShoppingReportUnitOfWork",
    "ShoppingReportUnitOfWorkFactory",
    "StoredShoppingReportIntegrityError",
    "validate_explanation_scope",
]
