"""Layer 2 - automatically find matching products.

Search, bounded detail collection, offer conversion, official cross-checking, and
specification normalization. Platform parsers and the controlled browser live in the
``platforms`` and ``browser`` adapter subpackages and are intentionally not re-exported here.
"""

from personal_shopping_agent.sourcing.collection import (
    CandidateDiscovery,
    NoCandidatesDiscoveredError,
    ProductDetailCollector,
    SearchDetailCollectionResult,
    SearchDetailCollectionService,
    SearchDetailUnitOfWork,
    SearchDetailUnitOfWorkFactory,
)
from personal_shopping_agent.sourcing.conversion import (
    ConvertedDetailBatch,
    DetailConversionError,
    DetailObservationConverter,
    NoDetailObservationsError,
    evidence_source_for_store,
)
from personal_shopping_agent.sourcing.cross_check import (
    EvidenceCheck,
    EvidenceCheckStatus,
    EvidenceCrossCheckBatch,
    EvidenceCrossCheckResult,
    EvidenceCrossCheckService,
    EvidenceCrossCheckUnitOfWork,
    EvidenceCrossCheckUnitOfWorkFactory,
    NoProductsForEvidenceCheckError,
    OfficialEvidenceIdentityMismatchError,
    OfficialEvidenceProvider,
    OfficialProductObservation,
    OfficialSpecificationObservation,
    ProductEvidenceChecker,
)
from personal_shopping_agent.sourcing.details import (
    PlatformDetailAdapter,
    PlatformDetailParseError,
    PlatformProductDetail,
    PlatformSpecificationObservation,
    PlatformVariantOption,
    ProductDetailService,
)
from personal_shopping_agent.sourcing.discovery import (
    CandidateDiscoveryService,
    CollectedPage,
    PageCollector,
    PlatformAccessRestrictedError,
    PlatformCandidate,
    PlatformSearchAdapter,
    PlatformSearchResult,
)
from personal_shopping_agent.sourcing.ingestion import (
    OfferIngestionResult,
    OfferIngestionService,
    OfferIngestionUnitOfWork,
    OfferIngestionUnitOfWorkFactory,
)
from personal_shopping_agent.sourcing.normalization import (
    MeasurementDefinition,
    NormalizedSpecification,
    NoSpecificationsForNormalizationError,
    ProductSpecificationNormalizer,
    SpecificationNormalizationBatch,
    SpecificationNormalizationResult,
    SpecificationNormalizationService,
    SpecificationNormalizationStatus,
    SpecificationNormalizationUnitOfWork,
    SpecificationNormalizationUnitOfWorkFactory,
    measurement_definition,
    normalize_measurement,
)
from personal_shopping_agent.sourcing.observations import (
    DetailObservation,
    PlatformObservationKind,
    PlatformObservationService,
    PlatformObservationStore,
    SearchObservation,
)

__all__ = [
    "CandidateDiscovery",
    "CandidateDiscoveryService",
    "CollectedPage",
    "ConvertedDetailBatch",
    "DetailConversionError",
    "DetailObservation",
    "DetailObservationConverter",
    "EvidenceCheck",
    "EvidenceCheckStatus",
    "EvidenceCrossCheckBatch",
    "EvidenceCrossCheckResult",
    "EvidenceCrossCheckService",
    "EvidenceCrossCheckUnitOfWork",
    "EvidenceCrossCheckUnitOfWorkFactory",
    "MeasurementDefinition",
    "NoCandidatesDiscoveredError",
    "NoDetailObservationsError",
    "NoProductsForEvidenceCheckError",
    "NoSpecificationsForNormalizationError",
    "NormalizedSpecification",
    "OfferIngestionResult",
    "OfferIngestionService",
    "OfferIngestionUnitOfWork",
    "OfferIngestionUnitOfWorkFactory",
    "OfficialEvidenceIdentityMismatchError",
    "OfficialEvidenceProvider",
    "OfficialProductObservation",
    "OfficialSpecificationObservation",
    "PageCollector",
    "PlatformAccessRestrictedError",
    "PlatformCandidate",
    "PlatformDetailAdapter",
    "PlatformDetailParseError",
    "PlatformObservationKind",
    "PlatformObservationService",
    "PlatformObservationStore",
    "PlatformProductDetail",
    "PlatformSearchAdapter",
    "PlatformSearchResult",
    "PlatformSpecificationObservation",
    "PlatformVariantOption",
    "ProductDetailCollector",
    "ProductDetailService",
    "ProductEvidenceChecker",
    "ProductSpecificationNormalizer",
    "SearchDetailCollectionResult",
    "SearchDetailCollectionService",
    "SearchDetailUnitOfWork",
    "SearchDetailUnitOfWorkFactory",
    "SearchObservation",
    "SpecificationNormalizationBatch",
    "SpecificationNormalizationResult",
    "SpecificationNormalizationService",
    "SpecificationNormalizationStatus",
    "SpecificationNormalizationUnitOfWork",
    "SpecificationNormalizationUnitOfWorkFactory",
    "evidence_source_for_store",
    "measurement_definition",
    "normalize_measurement",
]
